### ISSUE TITLE
More header information needed

### ISSUE THREAD

**Issue by tiagopereira** [sunpy/sunraster#100]
The IRIS level 2 FITS header contains a lot of information that is currently not being passed to `IRISMapCube` or `IRISSpectrogramCube`.  Information such as calibration version used, XCEN/YCEN, SAA, data histogram levels, etc. Most of this information may not be important for many users, but currently it is not accessible at all via IRISpy (only a handful of header keywords are passed into `meta`), and the only way to access it is to read the FITS file by hand.

And easy fix would be to just add more keywords into `meta`, but I wonder if we shouldn't have the whole header available, just in case? It also seems to me that converting from FITS header to a dictionary is re-inventing the wheel, since a good amount of code exists already in Astropy to deal with FITS headers. I know the focus is on the top-level objects to be agnostic of FITS, but it still feels a little ugly.

**Comment by steinhh** [comment]
I agree. At least some of that information may in some cases be essential for the understanding/interpretation of the data (e.g. SAA). But a few items should actually _not_ be available, in particular XCEN and YCEN. The coordinates of the center of the FOV is easily derivable from the WCS information, and it would be a pity if simple routines rely on those keywords, as this would make the routines incompatible with other fits files for absolutely no reason.

**Comment by DanRyanIrish** [comment]
This raises a good point that has largely been overlooked due to lack of priority.  I think it would be great if a list was compiled and discussed here of the keywords that should be in the meta.  Then once there's a consensus, the change can be made.

**Comment by mridullpandey** [comment]
hi @DanRyanIrish can you please suggest me key words that  is to be taken into in meta,and i'm  working on it

**Comment by nabobalis** [comment]
Moved to https://gitlab.com/LMSAL_HUB/iris_hub/irispy-lmsal/-/issues/13
