### ISSUE TITLE
Change name of Raster to SpectrogramCube and Sequence Refactor

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#142]
Wandering thoughts:

I prefer the sound of ```Raster``` and how it matches with ```RasterSequence``` but perhaps it over-specifies what the class is for.  ```Raster``` also supports sit-and-stare observations which may be confusing to users.  Or more likely, users will not realise that ```Raster``` is also the appropriate class for sit-and-stare observations.  The ```Raster``` class could also be a useful API standard for other objects such as a ```radiospectrogram```.

The downside of calling it ```Spectrogram``` is it could imply that it's only for 2D spectrograms.  This could be addressed by calling it ```SpectrogramCube```, but this more cumbersome.  Perhaps explaining the 3D nature of the class in documentation is sufficient.

Tentative proposed change:
* Rename ```Raster``` with ```Spectrogram```
* Define new abstract base class, ```SpectrogramABC```, that defines the ```Spectrogram``` API, similar the the ```NDCubeABC```.  This would allow ```radiospectrogram``` to use the same API even if the underlying implementation had to be altered.

This needs more thought and discussion.

**Comment by DanRyanIrish** [comment]
@hayesla do you have any thoughts on this?

**Comment by hayesla** [comment]
Hmm I see your point, and even myself when I think of `raster` I only think of a rastering spectrogram rather than a spectrogram ...

Along those lines I'm in favor of potentially following the similar API to NDCube - i.e having the `SpectrogramABC`?

**Comment by DanRyanIrish** [comment]
Proposed way forward after consultation with @hayesla.
* Rename ```Raster``` -> ```SpectrogramCube```
* Create new class, ```SpectrogramSequence```, for non-rastering sequence of ```Spectrogram```s without any raster-specific API.  (This should mainly be a copy-paste-delete job from ```RasterSequence```.
* Refactor ```RasterSequence``` to inherit from ```SpectrogramSequence```.  (This should mainly be a delete job.)
    * If slit step axis is sliced out, return a ```SpectrogramSequence```.
* Rename ```raster.py``` -> ```spectrogram.py``` and ```raster_sequence.py``` -> ```spectrogram_sequence.py```
    * While require find and replace in tests and elsewhere.

Features of ```SpectrogramSequence```
* Default common axis to None.  Hide is **kwargs if possible.
* ```spectral_axis```  (Rename from ```spectral``` to be consistent with ```Spectrum1D```.
* ```time```
* ```exposure_time```
* ```lat```
* ```lon```
* ```apply_exposure_time_correction```
* ```__str__```  (Separate all but the Class name in another property, ```_str``` so ```RasterSequence``` can use it.)
* ```__repr__```

Features of ```RasterSequence``` in addition to those inherited from ```SpectrogramSequence```:
* ```_raster_axis_name```
* ```_SnS_axis_name```
* ```_slit_step_axis_name```
* ```_slit_axis_name```
* ```_spectral_axis_name ```
* ```_single_scan_instrument_axes_types```
* ```raster_dimensions```
* ```SnS_dimensions```
* ```raster_world_axis_physical_types```
* ```SnS_world_axis_physical_types```
* ```raster_axis_extra_coords```
* ```SnS_axis_extra_coords```
* ```plot_as_raster```
* ```plot_as_SnS```
* ```slice_as_SnS```
* ```slice_as_raster```
* ```raster_instrument_axes_types```
* ```SnS_instrument_axes_types```
* ```__str__```
* ADD warning to ```__getitem__``` and instruct users to use ```slice_as_raster```.  Catch warning when calling ```__getitem___``` in ```SequenceSlicer.__getitem__```.
