### ISSUE TITLE
Finalize sunraster 0.1 docs.

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#143]

**Comment by kakirastern** [comment]
@DanRyanIrish Let me do some proofreading of the current docs on the `rasterpy` branch and make updates/modifications where necessary.

**Comment by DanRyanIrish** [comment]
@kakirastern I merged PR #148 so all the main API changes should now be in raster (except for the deletion of IRIS-specific code).  So if you are working on the docs, then you can issue your PR straight to the rasterpy branch and have the benefit of the CI.  I stress again that PR #148 changed the class and module names, so don't be surprised if there are a lot more failures all of a sudden.

**Comment by kakirastern** [comment]
Hi @DanRyanIrish No worries! Noted and I will be careful while working on the `rasterpy` branch.

**Comment by DanRyanIrish** [comment]
@kakirastern, I also just merged #147 so you will need to update your version of the rasterpy branch.  This however, should remove an failures due to IRIS-specific code.  Any that remain do need to be examined.

**Comment by kakirastern** [comment]
Okay, sure @DanRyanIrish 👍
