### ISSUE TITLE
Move calculation of uncertainty out of sunraster IRIS reader function

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#146]
Only do this once a function exists in ```sunkit-instruments``` that takes a sunraster object, calculates the uncertainty and can attach it to the object.

**Comment by nabobalis** [comment]
Do you mean?

```python
out_uncertainty = (u.Quantity(np.sqrt((data_nan_masked * unit).to(u.photon).value + readout_noise.to(u.photon).value ** 2), unit=u.photon,).to(unit).value)
```

That is in the SJI reader?

**Comment by DanRyanIrish** [comment]
> Do you mean?
> 
> ```python
> out_uncertainty = (u.Quantity(np.sqrt((data_nan_masked * unit).to(u.photon).value + readout_noise.to(u.photon).value ** 2), unit=u.photon,).to(unit).value)
> ```

Yes.  The reasoning was that for large IRIS data cubes, calculating the uncertainty during the read-phase made the reader slow.  If also could require a lot of memory.

> That is in the SJI reader?

Yes, I believe it is/was.  The uncertainty calculation should be valid for spectrograph and SJI.  The only detector-specific part was the readout noise value.  But that was looked up for the relevant detector before the calculation was done.

**Comment by nabobalis** [comment]
As I am removing the SJI reader from sunraster, what should happen to this issue?

**Comment by DanRyanIrish** [comment]
Oh, but you moved the spectrogram reader out as well, didn't you?  In that case this issue should be closed.
