### ISSUE TITLE
Set up testing against the ndcube 1.3 branch as well as ndcube master

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#151]
Hi @nabobalis, the recent API breaking changes to the ndcube master branch mean that testing ```sunraster``` against does not reflect whether ```sunraster``` will work with the stable release of ```ndcube```.  Is it possible to set up additional CI tests that use the ndcube 1.3 branch, so we can confirm that ```sunraster``` v0.1 will work with ```ndcube``` v1.3.x?  Is that a difficult job?

**Comment by nabobalis** [comment]
It should be done already. Let me check.

**Comment by nabobalis** [comment]
The dev build checks with master for astropy, ndcube and sunpy. I can remove them and leave ndcube?

**Comment by DanRyanIrish** [comment]
Actually if it's an easy thing, I actually need the tests to be against the 1.3 branch.  I want to make sure it's working with the planned but not yet released 1.3.1 version.  Is that difficult/possible?

**Comment by DanRyanIrish** [comment]
But keeping the tests against master as well is important to know for keeping up with ndcube 2.0 development.

**Comment by nabobalis** [comment]
It tests with the latest released version of ndcube normally and the master version too.

**Comment by DanRyanIrish** [comment]
OK.  So in order to be 100% sunraster works with ndcube 1.3.1 is to release it and then run the sunraster CI?

I guess that'll have to do.

**Comment by DanRyanIrish** [comment]
Thanks!

**Comment by nabobalis** [comment]
Well if the 1.3.1 changes are on master, they will be tested.

It should be possible to setup the branch test.

**Comment by DanRyanIrish** [comment]
OK, that'd be great.  Perhaps you could show me how to do that on Monday?

**Comment by nabobalis** [comment]
I opened a PR for this.
