### ISSUE TITLE
Replace master branch with rasterpy branch

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#153]
Currently master still holds IRISpy code, although all recent development has been performed on the rasterpy branch with a view to releasing ```sunraster``` which will not include any IRIS-specific code (except the spectrograph reader).

Before releasing ```sunraster``` v0.1, we need to replace master with rasterpy which will break any users' code.  However, this can be fixed by simply switching to the irispy branch where all the old IRISpy code will still be available.  (Reinstalling from the irispy branch may be required.)

**Comment by DanRyanIrish** [comment]
@tiagopereira do you have any concerns about this?

**Comment by Cadair** [comment]
I can't imagine that many people are rocking master branch installs of the old irispy :+1: from me for just making the switch.

**Comment by DanRyanIrish** [comment]
Thanks @Cadair.  Sounds like there's a consensus for the switch.  @tiagopereira agrees too.  Once once the docs are finalized and I've released ndcube 1.3.1, we can do the switch and then release sunraster 0.1.
