### ISSUE TITLE
Remove hyperlinks from titles

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunraster#166]
The hyperlinks in the titles leads to *really* bad contrast in the sidebar:

![image](https://user-images.githubusercontent.com/1391051/81055768-48d56b80-8ec1-11ea-9f8f-5fcdcd3c86bc.png)

While this really is a theme issue (sunpy/sunpy-sphinx-theme#112) you should mitigate it in the short term by just removing the hyperlinks.

**Comment by kakirastern** [comment]
Let me take this one on

**Comment by kakirastern** [comment]
Almost forgot about this, will get to this as soon as I can.
