### ISSUE TITLE
Spectrogram.__str__ hard-codes order of axis types

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#167]
[This line](https://github.com/sunpy/sunraster/blob/master/sunraster/spectrogram.py#L217) needs to prints out the axis types in the order which they are in the dat cube.  At the moment it assumes the order is always ```(Slit steps, Slit height, Spectral)```.

**Comment by kakirastern** [comment]
Looks like the solution is not immediately obvious... Guess will need to test the code with some spectrograms to find out the pattern or to get a sense.
