### ISSUE TITLE
Update sunraster to work with ndcube 2.0

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#177]
### Description

ndcube 2.0 is a major API-breaking update to ndcube.  The API will cause some code breakages in sunraster and so sunraster must be updated.

Make next version of sunraster only compatible with ndcube 2.x rather than having sunraster work with both ndcube 1.x and 2.x.

**Comment by godslayer201** [comment]
Hey Dan,

Can I start doing this in parts which require attention for ndcube? It would be a good chance for me to learn hands on for how sunraster really works with ndcube.
