### ISSUE TITLE
Documentation version for "latest" and broken links

### ISSUE THREAD

**Issue by ebuchlin** [sunpy/sunraster#194]
Hello,
The documentation for ["latest"](https://docs.sunpy.org/projects/sunraster/en/latest/) points to version "sunraster 0.1.dev349+gf27d784", I would expect it to be a more recent version than ["stable"](https://docs.sunpy.org/projects/sunraster/en/stable/) (which is 0.2.0).

In [DataClasses (stable)](https://docs.sunpy.org/projects/sunraster/en/stable/data_classes.html), most (or all) links to NDCube documentation are invalid (e.g. [NDCube coordinate transformations documentation](https://docs.sunpy.org/projects/ndcube/en/stable/ndcube.html#coordinate-transformations)), I guess that this is because the NDCube documentation pages have been split into smaller pages.

**Comment by nabobalis** [comment]
Thanks for the report, I will look into it and fix this.

The old documentation has been updated to the new ndcube version and that will be 0.3.0 coming out soon.

**Comment by nabobalis** [comment]
A new release of sunrsater is out. We have a new issue with RTD but it looks like the stable docs have updated ok.

**Comment by nabobalis** [comment]
RTD has been restored and with the new documentation. The links there should work.

If they are still broken, please re-open this PR and we can fix each case.
