### ISSUE TITLE
SPICE reader: take into account additional distortion information

### ISSUE THREAD

**Issue by ebuchlin** [sunpy/sunraster#216]
### Describe the feature

The current SPICE FITS files include "WCSDVARR" ImageHDUs to represent additional distortion information (see the [draft WCS IV paper](https://www.atnf.csiro.au/people/mcalabre/WCS/dcs_20040422.pdf)). Distortion from the instrument optics is already corrected in SPICE L2 FITS files, but the additional distortion in the WCSDVARR HDUs is the one that comes from spacecraft pointing changes, as obtained by the pipeline from the Solar Orbiter SPICE kernels.

#208 was about fixing the SPICE reader so that it does not fail on SPICE FITS files including HDUs for additional distortion information. This fix has been implemented by ignoring the WCSDVARR HDUs.

The SPICE FITS file reader should have the option to take into account this information instead of ignoring it.

### Proposed solution

How this should be done, and whether this should be part of sunraster or of a SPICE-specific package is still unclear. A possibility is to reproject on a non-distorted grid, but this has drawbacks, and it requires deciding what to do in problematic cases (e.g. when pointing jitter in the scanning direction is larger than the raster step).

**Comment by DanRyanIrish** [comment]
Now described by [Issue #9 in sospice](https://github.com/solo-spice/sospice/issues/9) and will be implemented there.
