### ISSUE TITLE
Invitation for co-authors of a JOSS paper

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#229]
### Provide a general description of the issue or problem.

Dear sunraster contributors,

@BaptistePellorceAstro @nabobalis @kakirastern @abit2 @Cadair @ehsteve @tiagopereira @shelbej @EdBehn @asainz-solarphysics @ebuchlin 

I am intending to submit a paper on sunraster to the Jounrnal of Open Source Software (JOSS).  As contributors to the sunraster code base I would like to invite you to be co-authors.  If you agree, please reply to this issue with your:
* Name you publish under
* Affiliation(s)
* Affiliation country(ies)
* ORCID (optional)

Thanks for your contributions!

**Comment by nabobalis** [comment]
Sure:

Nabil Freij
Lockheed Martin Solar and Astrophysics Laboratory, Palo Alto, CA, USA
Bay Area Environmental Research Institute, Moffett Field, CA, USA
0000-0002-6253-082X

**Comment by asainz-solarphysics** [comment]
Dear Daniel,

I don't think my contribution to sunraster to be significant enough to
deserve to be considered as co-author in the paper.
I do appreciate your email, though.

Congratulations for the job you all have done on sunraster, and especially
to Daniel for coordinating and managing all the efforts!!!

Best regards,

Alberto

**Comment by Cadair** [comment]
Sign me up, you have the deets already :p

**Comment by DanRyanIrish** [comment]
I have just submitted the sunraster paper to JOSS.  Thanks to all those who agreed to be co-authors.
