### ISSUE TITLE
Time-Dependent IRIS Effective Areas

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#27]
Enable time-dependent effective areas to be derived using get_iris_response() in iris_tools in the same way that it is done in SSW.  See iris_get_response in SSW, a version of which can be found here: https://sohowww.nascom.nasa.gov/solarsoft/iris/idl/lmsal/util/iris_get_response.pro

**Comment by kakirastern** [comment]
Hi, I am interested in offering help on this issue if it's not yet taken?

**Comment by DanRyanIrish** [comment]
Hi @kakirastern.  More help on this issue would be great as our initial work has stalled and I think it's fair to say we need another injection over effort to move it forward.  I will set up a new branch to which we can make PRs to that maintains the work already done.

**Comment by iamharshgupta** [comment]
Hi, I would like to work on this issue so do I start off with it ?

**Comment by kakirastern** [comment]
Hi @iamharshgupta, I have expressed interest in this issue first so would like to give it a try...

**Comment by DanRyanIrish** [comment]
Hi @iamharshgupta.  I'm thrilled to hear you are interested in contributing!  We can always use more help!  When it comes to this issue however, @kakirastern has already started working on it and I think it would be more efficient to have one person working on this issue at a time.

However, there are plenty of things to still get involved in.  Would you be interested in helping with an issue in the ```ndcube``` package?  ```ndcube``` is the package upon which IRISpy principally depends.  I have one in mind: https://github.com/sunpy/ndcube/issues/149.  If so, we could start a conversation on that issue page with @Cadair one how we should start going about it.

**Comment by DanRyanIrish** [comment]
@kakirastern I know I promised to set up a branch to which you can pull and open a PR to.  I'll do that this evening and let you know when it's available.

**Comment by kakirastern** [comment]
@DanRyanIrish Yeah, been waiting for it... I appreciate your reply! Just let me know when it is ready.

**Comment by iamharshgupta** [comment]
Hi @DanRyanIrish , could you please give me your riot username so I could talk to you there ?

**Comment by DanRyanIrish** [comment]
Hi @kakirastern.  I had permissions issues over the weekend which meant I couldn't create the new branch for you like I said.  I've sorted that now though the new branch is ```time_dependent_response``` in the sunpy/irispy repo:
https://github.com/sunpy/irispy/tree/time_dependent_response
So you should checkout that branch in your own repo and start committing to it.  Then push it to your own fork and when the time comes open a PR to that branch in the sunpy/irispy repo, not the master branch which is the default.  I can talk you through this process on riot is you like.

**Comment by kakirastern** [comment]
Hi @DanRyanIrish. Yup, I would definitely need some kind of a walking through the process, as I haven't tried something similar before. But I will give it a try between now and when we meet on Riot say sometime during day time in EDT over the next few days to see if I can figure it out on my own first.

**Comment by kakirastern** [comment]
Just checked-out the branch [https://github.com/sunpy/irispy/tree/time_dependent_response](https://github.com/sunpy/irispy/tree/time_dependent_response) and have set up tracking upstream from my local branch to my own fork at [https://github.com/kakirastern/irispy/tree/time_dependent_response](https://github.com/kakirastern/irispy/tree/time_dependent_response) Will start committing to it soon.

**Comment by DanRyanIrish** [comment]
Also, the original IDL function that this project is rewritting is [here](https://www.heliodocs.com/xdoc/xdoc_print.php?file=$SSW/iris/idl/lmsal/calibration/fit_iris_xput.pro).  Don't worry if it's hard to understand, even if you know a bit of IDL.  But comparing it with what Alberto has written in Python might be helpful in understanding what the code is supposed to do.

**Comment by kakirastern** [comment]
Yup, I have removed the original `iris_tool.py` file and replaced it with the renamed `mi_iris_tools.py` now known as `iris_tool.py` in PR #108.

**Comment by DanRyanIrish** [comment]
Achieved in PR #119
