### ISSUE TITLE
How to deal with time since epoch (WCS standard) and date/time in NDCube/SJICube.

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunraster#69]
The use case is ```SJICube```.  The WCS includes time in seconds since epoch.  But users will likely want to be able to use date/time when slicing, indexing etc.  Should another layer of abstraction be built to allow users to interact with time in the WCS not only as seconds since epoch, but as date/time based on some epoch in the metadata?  Or should we have WCS time be only seconds since epoch while simultaneously having a time extra coordinate giving time in date/time?  And if the former, should that functionality exist in ```NDCube``` or ```SJICube```?

I propose that the former functionality not be included in ```NDCube``` (nor even in ```SJICube```) for the time being as it is complicated to implement seamlessly and will only be applicable if the WCS includes time.  This makes it not general or minimalist which is the philosophy of ```ndcube```.  Instead I propose that we use the extra coordinate option for ```SJICube```.  This is a little messy as it will mean that we have two time coordinates: seconds since epoch in the WCS and date/time as an extra coordinate.  However, this could potenitally end up being useful.  It's also the simplest implementation and until we have feedback from many IRISpy users saying that a time extra coordinate in ```SJICube``` is far too confusing/cumbersome I think the effort involved in implementing an alternative is not time wisely spent.

However, to ensure ```SJICube``` does contain this extra coordinate where possible based on user input/FITS file contents, the ```SJICube.__init__``` should attempt to provide a time extra coordinate where possible.  In practice this means ```SJICube.__init__``` should:
* Check whether a ```"TIME"``` extra coordinate has been supplied by the user.
* If there is no ```"TIME"``` extra coordinate, it should look to see whether there is a time object in the ```meta``` under the key ```"STARTOBS"```.
  * If so, it should generate a ```"TIME"``` extra coord based on the the epoch given by ```"STARTOBS"``` and the time values for each pixel given by the WCS object.
  * If there is a ```"TIME"``` extra coordinate, the meta should be searched for the key ```"STARTOBS"```.
    * If it doesn't exist, it should be derived from the 0th entry of the ```"TIME"``` extra coordinate minus the WCS time value of the 0th pixel.
* If there is no ```"TIME"``` coordinate  and no ```"STARTOBS"``` metadatum, then a warning should be raised saying something like "No ```"STARTOBS"``` provided or derived.  Date/time of measurements cannot be supplied as an extra coordinate."
This way, a ```"TIME"``` extra coordinate and a ```"STARTOBS"``` metadatum always exist when they are derivable.  However, it does allow the user to continue without them with a warning.

**Comment by steinhh** [comment]
I'm not very heavily involved in irispy (to say the least), but I have read way too much about FITS/WCS standards not to comment on this ;-). I think it would be a good idea if the routines are made as generic as possible - i.e. that they will work with FITS files that adhere to the official FITS standards as well as IRIS-specific standards. That way, it'll be easier - at some point in the distant future - to either a) promote some of the code into a more generic pyfits/astropy/whatever library or b) simply take advantage of more generic (existing(?) or yet to be written by others) code. Both a and b would result in leaner irispy code. So here are a few wishes/suggestions from my standpoint:

"TIME" is deprecated as a coordinate name, but allowed for backwards compatibility. "UTC" (like it or not) is the standard (Sect. 4.1.1 of Rots et al, attached). So I propose that routines will recognise "UTC" as well as "TIME".

The time reference value is supposed to be given with one of the three keywords MJDREF, JDREF (both float-valued) or DATEREF (datetime-valued) (ibid. Sect. 4.1.2). So I propose that these should be recognised as well - actually with _precedence_ over STARTOBS for compatibility with future data sets where STARTOBS might have another, non-IRIS-specific meaning.

Recognising these WCS-standard "aliases" (from the IRIS POV) shouldn't add more than a line or two in the code :)

Cheers,
Stein
[_IV_Time-coord-in-FITS.pdf](https://github.com/sunpy/irispy/files/1918902/_IV_Time-coord-in-FITS.pdf)

**Comment by steinhh** [comment]
By the way, what does "a coordinate giving time in date/time" actually mean - a string-valued coordinate? And what should it be called?

**Comment by DanRyanIrish** [comment]
Hi @steinhh.  Thanks so much for your contribution.  I agree that we should strive for generality as much as possible and leveraging other packages, thereby keeping ```irispy``` code-base leaner.  In fact, it was out of this philosophy that the ```ndcube``` package, on which ```irispy``` depends, was created.  Some of your comments about how WCS handles time I was not aware of.  So thanks so much for highlighting that here.  I think there is a valuable discussion to be had coming out of this about whether infrastructure along the lines you describe should be developed in ```ndcube```.

For ```irispy``` though, we know the conventions regarding how the data and metadata is stored and labelled and so I think we can afford not to be general.  In fact, that's the point of the ```irispy``` classes: to handle only the aspects specific to IRIS and leave the general stuff to ```ndcube```.  So I think in the ```SJICube``` class we are OK to use ```"TIME"``` and ```"STARTOBS"``` as we know this is how the data is labelled.

Thanks again for your thought-provoking comments.
