### ISSUE TITLE
Add a catch-all loader for IRIS FITS files

### ISSUE THREAD

**Issue by tiagopereira** [sunpy/sunraster#80]
It would be nice to have a generic load function to load any kind of IRIS file into the appropriate objects. E.g.:

    data = irispy.read_iris("some_file.fits")

And the type of data would be either an `IRISSpectrograph`, `IRISSJICube` or other appropriate class. This could work for any level file (assuming there are loader functions for all) and any instrument, since this information is all in the header file. This  would be optional and would not return a new class, but just redirect to the appropriate reader. It could also made future-proof by allowing it to read formats other than FITS if necessary. It is similar to what the IDL object interface does, and would be natural for people switching from IDL.

**Comment by nabobalis** [comment]
Moved to https://gitlab.com/LMSAL_HUB/iris_hub/irispy-lmsal/-/issues/4
