### ISSUE TITLE
Make loading IRISSpectrograph more memory efficient

### ISSUE THREAD

**Issue by tiagopereira** [sunpy/sunraster#82]
I'm finding that `IRISSpectrograph`, or `read_iris_spectrograph_level2_fits()` takes a very long time to load and has a very high memory usage. Loading a moderate size IRIS raster in my laptop, which only has 8 GB of RAM, leads to lots of swapping and the machine nearly crawls to a halt. 

Testing in different machines, I find the RAM that `read_iris_spectrograph_level2_fits()` uses is between 3-4 times the total size of the IRIS level 2 FITS file. A 606 MB file took about 1.5 GB of RAM, while a 2.6 GB file took 10GB. This is very inefficient, not to mention slow (even if the machine has enough RAM). 

Looking in the code, I suspect these lines are the most problematic:
https://github.com/sunpy/irispy/blob/bbd194205c1dd815230925ad676a286f572bb28c/irispy/spectrograph.py#L562-L564 

There should be a way to load it with `memmap`, and ideally it should be the default.

In addition, the uncertainty will perform many operations on all data points from the file:

https://github.com/sunpy/irispy/blob/bbd194205c1dd815230925ad676a286f572bb28c/irispy/spectrograph.py#L596-L598

This is a huge burden for something of marginal value. 

The loading of `IRISSpectrograph` should be as lightweight as possible. People may use it just to look at what's inside.

**Comment by DanRyanIrish** [comment]
Hi @tiagopereira.  I've opened a PR irradicating the ```deepcopy``` you highlighted above in a hope of reducing the RAM requirements of the ```read_iris_spectrograph_level2_fits()```.  Could you give it a quick review and play it with to see if it improves the cases you tested at all?

Another thing we could do is have the uncertainty derivation be optional so the user can turn it off if they don't have a lot of RAM.  This will require some changes to other parts of the code base where it is assumed ```uncertainty``` will always exist.  But it could be done.  We could then also add a ```derive_uncertainty``` method which populates this attribute if the user later decides they want it, say after they have extracted a region of interest and RAM considerations are no longer so important.  I can open a separate PR for that change when I get a chance.

Does this sound like a good way forward for now?

**Comment by tiagopereira** [comment]
Hi @DanRyanIrish, thanks for this. I don't have any time this week but will look at this next week. Please ping me again if I forget about this.

**Comment by tiagopereira** [comment]
Here are some timings and memory usage of the spectrograph class. All these numbers were from my laptop, so obviously only relative differences matter. Numbers are from macOS Activity Monitor, and might differ from those of top.

The file I tested was `myfile = 'iris_l2_20180102_153155_3610108077_raster_t000_r00000.fits'`, a 602 MB file that should take about twice that amount of RAM once loaded (because of the scaling). This is a medium-sized file, it probably gets worse with larger files.
```
from irispy.spectrograph import read_iris_spectrograph_level2_fits

def load():
    return read_iris_spectrograph_level2_fits(myfile)
```

#### Before PR #93 
* Peak RAM usage (loading): ~4 GB, 
* RAM usage after load: 2,82 GB
* RAM after deleting object: 176 MB

```
%timeit -n 5 load()
20.6 s ± 2.29 s per loop (mean ± std. dev. of 7 runs, 5 loops each)

u = load()
%timeit repr(u)
608 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```


#### With PR #93 
* Peak RAM usage (loading): 2,82 GB, 
* RAM usage after load: 2,82 GB
* RAM after deleting object: 176 MB

```
%timeit -n load()
8.32 s ± 451 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

u = load()
%timeit repr(u)
608 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

#### With PR #93 , but setting `uncertainty=None`
* Peak RAM usage (loading): 1,64 GB, 
* RAM usage after load: 1,64 GB
* RAM after deleting object: 176 MB

```
%timeit -n load()
1.99 s ± 49.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

u = load()
%timeit repr(u)
284 ms ± 6.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
#### With PR #93 , but setting `uncertainty=None` and `memmap=True`
* Peak RAM usage (loading): 480 MB, 
* RAM usage after load: 480 MB
* RAM after deleting object: 176 MB

```
%timeit -n load()
904 ms ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

u = load()
%timeit repr(u)
140 ms ± 5.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

#### Simply loading all data to memory with `astropy.io.fits`

* Peak RAM usage (loading): ~1,30 GB
* RAM usage after load: ~1,30 GB

```
%timeit test()  # open fits and load data from all windows
1.84 s ± 77.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit test_memmap()  # same test, but with memmap
14.9 ms ± 675 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

#### Summary

It appears getting rid of `uncertainty` results in using about half of the RAM (as expected) and speeds up the loading by a factor of 4. Also the time of doing `repr`, which also seemed rather long to me, is reduced by half. Surprisingly, with all the additional metadata and operations, using IRISpy without `uncertainty` only carries a small time penalty vs. loading all data directly from the FITS. Using `memmap` further reduces loading time by half, and RAM by about 1 GB (although at the price of not having scaled data and eventually having to load it into RAM when necessary). 
I suggest setting `uncertainty` to be optional, with the default to `None`, and also make `memmap` at least an option, if not the default.

**Comment by DanRyanIrish** [comment]
Thanks @tiagopereira for this.  I think it certainly shows there is scope to improve the performance.  I think the size of the data compared to typical laptop hard drives shows that even for IRIS, there may be value to consider a dask-integrated ndcube in the future, or even more cloud-style computing like is done with pangeo.  But that is definitely beyond a longer term discussion.

Regarding your specific suggestions, we could certainly implement something along these lines.  We should start with making the uncertainty optional, but my instinct would be to have the default be to perform the full uncertainty calculations.  Then based on the users' own system resources, they can discard the functionalities they don't want/can't handle, in this case, the uncertainty calculation.  Having the default this way will mean less hassle for IRISpy development in the future as machines become more powerful and/or we move to a more server-based analysis paradigm.

I'm less crazy about the ```memmap``` idea because for the spectrograph, the DN have a well-defined physical meaning in a way that is not true for SJI.  So that lack of scaling matter more.  However, from your numbers I can see that such an option could still be very useful to some users.  It would be good to hear a bit more detail about an example workflow in which the ```memmap``` option would be used.  How, for example would things like line fitting, data visualisation, etc. fit into this workflow?  My understanding is that to perform these tasks the data must be read into RAM.

**Comment by tiagopereira** [comment]
I think it is unfortunate the way `memmap` works with the FITS scaling (that no scaling on the fly is possible), and that IRIS level 2 FITS files are scaled. Level 3, for example, don't have scaling and `memmap` can be used all the time. 

For many workflows using `memmap` and unscaled units works fine. You can still make fits and so on and just scale the quantities that are a function of the intensity. Especially for visualisation, often you want to look at movies and don't care what the absolute units are. Even if you have to load all the data into memory, with `memmap` it only takes half the RAM of the scaled version (although some programs might not like to deal with integers). 

The big advantage of `memmap` is being able to deal with files much larger than the system memory, e.g. play movies of large data cubes that we don't wish in memory all the time. For comparison, the default SSWIDL IRIS interface uses a `memmap` equivalent (`assoc`) by default, and only loads/scales the data when the `/load` keyword is specified. This is not usually a problem for IRIS (although some files are in the GB range), but for ground-based or future space missions it may. We routinely work with SST files that can be up to 100 GB. Loading all and especially computing quantities for every pixel is just not possible.

For IRIS, a user may not necessarily want to load *all* wavelength regions, and only work with a few. I for one don't remember a single time that I had to use all wavelength windows. So why spend the effort at loading and computing uncertainties for the other regions?

**Comment by DanRyanIrish** [comment]
This is very interesting and raises some points I haven't given a lot of thought.  Currently the visualisation tools available via ```ndcube``` require reading everything into memory.  However, all those visualisation tools to supplied via a mixin class.  So it would be simple to replace this with a ```NDCubeMemmapPlotMixin``` that has the infrastructure you're talking about.  That doesn't necessarily mean that it would be work to write that class in the first place though...

And it's good to hear that fitting is not a big deal with ```memmap``` either.

Regarding the wavelength windows, we have a ready-made solution.  The ```read_iris_level2_fits``` function should have a ```spectral_windows``` kwarg that allows the user to only read the windows he/she is interested in.  So with or without```memmap``` or ```uncertainty``` the user can already reduce their RAM usage that way.

**Comment by Cadair** [comment]
@DanRyanIrish the plotting tools would work transparently with memmapped numpy arrays, no modifications would be needed.

**Comment by tiagopereira** [comment]
Is there a verdict regarding the loading of the uncertainty? I'm organising a course right now, and even for SJI files, computing the uncertainty leads to a significant slowdown. It would be great if this could be optional, and even better if off by default. 

As I see it, most workflows start by data exploration and further analysis such as error and uncertainty estimation only comes at a later stage. So for most of the time people are calculating something they won't use. I think it is fairly easy to judge the noise level in spectra and images before having to do a sqrt(N) on every single pixel.

**Comment by Cadair** [comment]
sorry if I am missing something obvious, but could we not move the `uncertainty` calculation into a property? and then stick [this decorator](http://docs.astropy.org/en/stable/api/astropy.utils.decorators.lazyproperty.html#astropy.utils.decorators.lazyproperty) on it so it's only computed once?

**Comment by DanRyanIrish** [comment]
Sorry I haven't replied to this.  I'll be back from the rocket campaign next week and will catch up with this.

**Comment by DanRyanIrish** [comment]
@Cadair's suggestion looks like an exciting one.  However, how would this work for ndcube?  Presumably it would require less work in the long run to have ndcube support this and IRISpy inherit it.  But a couple questions spring to mind.  The slicing slices the uncertainty array as well as the data array.  Does this mean the uncertainty will be calculated the first time slicing is done?  If so that would presumably make the first slicing operation very slow?

**Comment by nabobalis** [comment]
Moved to https://gitlab.com/LMSAL_HUB/iris_hub/irispy-lmsal/-/issues/14
